### ISSUE TITLE
env variable don't work with docker compose

### ISSUE THREAD

**Issue by gkdgo** [zincsearch/zincsearch#898]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
run zincsearch by docker compose

**What action did you take?**
run 
```yaml
version: '3'

services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    container_name: zincsearch
    ports:
      - 4080:4080
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=111
      - ZINC_FIRST_ADMIN_PASSWORD=111
      - ZINC_SWAGGER_ENABLE=true # http://localhost:4080/swagger/index.html
    volumes:
      - ./data:/data
  ```
**What action/response/output did you expect?**
go to http://localhost:4080/ui/login use 111/111 log in

**What actually happened?**
<img width="233" alt="iShot_2023-06-27_16 59 47" src="https://github.com/zincsearch/zincsearch/assets/55651847/698c95ae-4d75-4aa2-bfa5-c55f7c74f0f1">

**What version of ZincSearch are you using?**
0.4.7

**Which service(s) is this relate to?**
This could be GUI or API
no sure
